//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Proje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEgitimlerim
    {
        public int ID { get; set; }
        [Required (ErrorMessage ="Bu Alaný Boþ Geçemezsiniz")] 
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public string AltBaslik2 { get; set; }

        [StringLength(10, ErrorMessage ="Lütfen En fazla 10 Karakterlik Bir Veri Giriþi Yapýnýz")]
        public string GNO { get; set; }
        public string Tarih { get; set; }
    }
}
